### PR TITLE
Fixed ReplacingMergeTree EngineSpec parsing: is_deleted column presence caused error

### PR DESCRIPTION
**Pull request by AlexTheKing**
## Summary

Column for marking rows as deleted ([**is_deleted** column](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replacingmergetree#is_deleted)) of **ReplacingMergeTree**  was not anyhow handled during EngineSpec parsing resulting in runtime exception like below:

```
java.lang.IllegalArgumentException: Expect list size 0 or 1, but got 2
at xenon.clickhouse.parse.ParseUtils$.seqToOption(ParseUtils.scala:32)
at xenon.clickhouse.parse.AstVisitor.visitEngineClause(AstVisitor.scala:78)
at xenon.clickhouse.parse.SQLParser.$anonfun$parseEngineClause$1(SQLParser.scala:30)
at xenon.clickhouse.parse.SQLParser.parse(SQLParser.scala:49)
at xenon.clickhouse.parse.SQLParser.parseEngineClause(SQLParser.scala:30)
at xenon.clickhouse.spec.TableEngineUtils$.resolveTableEngine(TableEngineUtils.scala:24)
at xenon.clickhouse.ClickHouseCatalog.loadTable(ClickHouseCatalog.scala:133)
at xenon.clickhouse.ClickHouseCatalog.loadTable(ClickHouseCatalog.scala:36)
at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:583)
at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:566)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
at java.lang.Thread.run(Thread.java:748)
```

## Checklist
Delete items not relevant to your PR:
- [X] Unit tests covering the common scenario was added

### CODE REVIEW

**Comment by AlexTheKing** [comment]
I'm not sure whether I have something to do with the ClickHouse Cloud tests :)

**Comment by pan3793** [comment]
@AlexTheKing the cloud test failure is irrelevant.

instead of dropping the is_deleted column info directly, I'm wondering if we can reserve such info in `ReplacingMergeTreeEngineSpec`, then we can use such info to filter/process the deleted rows on the spark side later if wanted.

**Comment by AlexTheKing** [comment]
I can add changes to preserve it in ReplacingMergeTreeEngineSpec if needed

**Comment by AlexTheKing** [comment]
Added one more commit: now preserving is_deleted column in spec, also added the same for `ReplicatedReplacingMergeTree` (it had the same issue)

**Comment by AlexTheKing** [comment]
I fixed test & style, should like OK now

**Review by pan3793 — APPROVED** [review]

**Comment by mshustov** [comment]
@mzitnik PTAL

**Pull request merged**
